.\" Process this file with
.\" groff -man -Tascii advpng.1
.\"
.TH AdvancePNG 1 "01 Agosto 2002"
.SH NAME
advpng \- png compression utility
.SH SYNOPSIS
.B advzip [-l, --list] [-z, --recompress]
.B [-0, --shrink-0] [-1, --shrink-1] [-2, --shrink-2] [-3, --shrink-3]
.B [-f, --force]
.B [-q, --quiet] [-h, --help] [-V, --version]
ARCHIVES... [FILES...]
.SH DESCRIPTION
The main purpose of this utility is to recompress png files
to get the smallest possible size.
.SH OPTIONS
.B -l, --list ARCHIVES...
List the content of the specified files.
.TP
.B -z, --recompress ARCHIVES...
Recompress the specified archives.
If the -1, -2, -3 options are specified is used the smallest file choice from the
previous compressed data and the new compression.
If the -0 option is specified the archive is always rewritten without any compression.
.TP
.B -0, --shrink-0
Set the compression level to "none". The file are only stored and not compressed.
.TP
.B -1, --shrink-1
Set the compression level to "normal". This is the default level of compression.
.TP
.B -2, --shrink-2
Set the compression level to "extra". It's SLOW.
.TP
.B -3, --shrink-3
Set the compression level to "extreme". It's VERY SLOW.
.TP
.B -f, --force
Force the use of the new file also if it's bigger.
.SH COPYRIGHT
Copyright (C) 2002 Andrea Mazzoleni
