.TH "AdvanceSCAN Installation" 1
.SH NAME
advscan \(hy AdvanceSCAN Installation
.PP
As root or user type:
.PP
.RS 4
./configure
.PD 0
.PP
.PD
make
.PD 0
.PP
.PD
.RE
.PP
and as root to install the programs and the documentation
type:
.PP
.RS 4
make install
.PD 0
.PP
.PD
.RE
.PP
then change the example configuration file advscan.rc for
AdvanceSCAN to your requirements.
.PP
The documentation is in the man pages:
.PP
.RS 4
man advscan
.PD 0
.PP
.PD
man advdiff
.PD 0
.PP
.PD
.RE
