.TH "AdvanceSCAN Installation" 1
.SH NAME
advscan \(hy AdvanceSCAN Installation
.PP
As root or user type:
.PP
.RS 4
./configure
.PD 0
.PP
.PD
make
.PD 0
.PP
.PD
.RE
.PP
To check the generated executable type:
.PP
.RS 4
make check
.PD 0
.PP
.PD
.RE
.PP
and as root to install the programs and the documentation
type:
.PP
.RS 4
make install
.PD 0
.PP
.PD
.RE
.PP
then change the example configuration file advscan.rc for
AdvanceSCAN to your requirements.
.PP
The documentation is in the man pages:
.PP
.RS 4
man advscan
.PD 0
.PP
.PD
man advdiff
.PD 0
.PP
.PD
man advzip
.PD 0
.PP
.PD
man advpng
.PD 0
.PP
.PD
man advmng
.PD 0
.PP
.PD
.RE
.SH REQUIREMENTS 
To build AdvanceSCAN you need a C/C++ compiler.
.PP
Tested with the following compilers on a GNU/Linux
environment :
.PP
.RS 4
GNU gcc 2.95.3
.PD 0
.PP
.PD
GNU gcc 3.0.4
.PD 0
.PP
.PD
GNU gcc 3.1, 3.1.1
.PD 0
.PP
.PD
GNU gcc 3.2, 3.2.1
.PD 0
.PP
.PD
.RE
.PP
The build process in DOS and Windows isn\(cqt tested. The DOS
and Windows binaries are generated in Linux cross compiling.
If you have the cross compiler installed, you can try the
configure.msdos and configure.windows configuration scripts.
