.TH "AdvanceSCAN Roms Manager" 1
.SH NAME
advscan \- AdvanceSCAN Roms Manager
.PP
AdvanceSCAN is a command line rom manager for AdvanceMAME,
AdvanceMESS and any other MAME derivative.
.PP
It runs in Linux, Mac OS X, DOS, Windows and in all the other
Unix like platforms.
.PP
The official site of AdvanceSCAN is:
.PP
.RS 4
http://www.advancemame.it
.RE
.PP
This package contains:
.RS 4
.PD 0
.HP 4
.I advscan
Rom manager
.HP 4
.I advdiff
Diff utility for rom list files
.PD
.RE
