.TH "The AdvanceSCAN roms manager" 1
.SH NAME
advmame \(hy The AdvanceSCAN roms manager
.PD
.RE
.PP
AdvanceSCAN is a command line rom manager for MAME, MESS,
AdvanceMAME, AdvanceMESS and Raine for Unix and DOS.
.PP
It also contains a recompression utility for your .ZIP roms, .PNG
snapshots and .MNG clips. It can also generate differential rom list.
.PP
The official site of AdvanceSCAN is :
.PP
.RS 4
http://advancemame.sourceforge.net
.RE
.PP
This package contains :
.RS 4
.PD 0
.HP 4
.I advscan
Rom manager
.HP 4
.I advdiff
Diff utility for rom info files
.HP 4
.I advzip
Recompression and test utility for zip files
.HP 4
.I advpng
Recompression utility for png files
.HP 4
.I advmng
Recompression utility for mng files
