.TH "The AdvanceSCAN roms manager" 1
.SH NAME
advscan \(hy The AdvanceSCAN roms manager
.PP
AdvanceSCAN is a command line rom manager for MAME, MESS,
xmame, AdvanceMAME, AdvanceMESS and Raine.
.PP
It runs in Linux, Mac OS X, DOS, Windows and in all the other
Unix like platforms.
.PP
The official site of AdvanceSCAN is:
.PP
.RS 4
http://advancemame.sourceforge.net
.RE
.PP
This package contains:
.RS 4
.PD 0
.HP 4
.I advscan
Rom manager
.HP 4
.I advdiff
Diff utility for rom list files
.PD
.RE
